name: Web server

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # environment: mrlectus

    strategy:
      matrix:
        node-version: [22.x]
    env:
      ENV_FILE: ${{ secrets.ENV }}
    steps:
    - name: do checkout
      uses: actions/checkout@v4
    - name: ssh into server
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: "unnecessary"
    - name: known host
      shell: zsh
      run: ssh-keyscan -H ${{ secrets.PHOST }} >> ~/.ssh/known_hosts
    - run: rsync -avz . 'root@${{secrets.PHOST}}':/root/deploy/ --exclude={node_modules,.git}
    - run: echo '${{ env.ENV_FILE }}' > .env
    - run: cat .env
    - run: rsync -avz .env 'root@${{secrets.PHOST}}':/root/deploy/
    - name: install dependencies
      run: |
        ssh 'root@${{ secrets.PHOST }}' "cd deploy; ~/.bun/bin/bun install; PORT=4000 pm2 restart --interpreter ~/.bun/bin/bun src/index.ts --name server"
