name: Web server

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # environment: mrlectus

    strategy:
      matrix:
        node-version: [18.x, 22.x]
    env:
      AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      DB_URL: ${{ secrets.DB_URL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}

    steps:
    - name: do checkout
      uses: actions/checkout@v4
    - name: Setup Npm
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Bun
      run: npm install -g bun
    - run: bun -v
    - name: Install dependency
      run: bun install
    - run: env
