name: Web server

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # environment: mrlectus

    strategy:
      matrix:
        node-version: [22.x]
    env:
      AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      DB_URL: ${{ secrets.DB_URL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}

    steps:
    - name: do checkout
      uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install dependency
      run: bun install
    - name: Ssh into server
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: "unnecessary"
    - name: Known host
      run: ssh-keyscan -H ${{ secrets.PHOST }} >> ~/.ssh/known_hosts
    - run: rsync -avz . 'root@${{secrets.PHOST}}':/root/deploy/ --exclude={node_modules,.git}
    - name: install server dependencies
      run: |
        ssh 'root@${{ secrets.PHOST }}' "cd deploy; ./.bun/bin/bun install"
