name: Web server

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 22.x]
    env:
      API_VER: "22.04"

    steps:
    - name: do checkout
      uses: actions/checkout@v4
    - name: Setup Bun
      run: curl -fsSL https://bun.sh/install | bash
    - run: source /home/runner/.bashrc
    - run: bun -v
    - run: echo ${{env.API_VER}}
