name: Web server

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 22.x]
    env:
      AWS_ACCESS_KEY:  ${{vars.AWS_ACCESS_KEY}}
      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}

    steps:
    - name: do checkout
      uses: actions/checkout@v4
    - name: Setup Npm
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Bun
      run: npm install -g bun
    - run: bun -v
    - name: Install dependency
      run: bun install
    - run: echo ${{ env.AWS_ACCESS_KEY }}
    - run: echo ${{ env.AWS_ACCESS_KEY }}
    - run: echo ${{ vars.AWS_ACCESS_KEY }}
    - run: echo ${{ secrets.AWS_SECRET_KEY }}
    - run: env
