name: Web server

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 22.x]
    env:
      API_VER: "22.04"

    steps:
    - name: do checkout
      uses: actions/checkout@v4
    - name: Setup Npm
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Bun
      run: npm install -g bun
    - run: bun -v
    - name: Install dependency
      run: bun install
    - run: echo ${{env.API_VER}}
